# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Session-Memcached
version:      0.03
version_from: lib/Apache/Session/Memcached.pm
installdirs:  site
requires:
    Apache::Session:               1.54
    Cache::Memcached:              1.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
